Parallel pagerank: /home/ecat/nikos/parallel/src/ntw_crs.c File Reference
ntw_crs.c File Reference
The definitions for the functions declared at ntw_crs.h .
#include "../include/ntw_crs.h"
#include <stdio.h>
#include <stdlib.h>
Functions
ntw_crs * NTW_CRS_new (const uint32_t nodeNum, const uint32_t edgeNum, uint32_t rowPtr[static nodeNum+1], uint32_t colInd[static edgeNum], double val[static edgeNum])
Creates a new CRS structure to store a matrix.
void NTW_CRS_free (ntw_crs *crs)
Unloads a ntw_crs from memory (frees allocated memory).
ntw_crs * NTW_CRS_newTranspose (const ntw_crs crs[static 1])
Creates a new ntw_crs storing the transpose of crs.
void NTW_CRS_cmult (ntw_crs crs[static 1], const double c)
Multiplies the values of the sparse table in the CRS form crs with the constant value c.
void NTW_CRS_vmult (const ntw_crs crs[static 1], const double vector[static 1], double product[static crs->node_num])
Calculates the product of the CRS table crs with the vector and stores the result in product.
double * NTW_CRS_vmultAlloc (const ntw_crs crs[static 1], const double vector[static 1])
Calculates the product of the CRS table crs with the vector and return the result.
void NTW_CRS_vmultTranspose (const ntw_crs crs[static 1], const double vector[static 1], double product[static 1])
Calculates the product of the transpose of the CRS table crs with the vector and stores the result in product.
void NTW_CRS_rowNorm (ntw_crs crs[static 1])
Normalizes the rows of the CRS table so they sum to one.
void NTW_CRS_rowNormUnif (ntw_crs crs[static 1])
Normalizes the rows of the CRS table giving all the edges in each row the same value in order to sum to one.
void NTW_CRS_colNorm (ntw_crs crs[static 1])
Normalizes the columns of the CRS table so they sum to one.
uint32_t NTW_CRS_getEmptyRowsNum (const ntw_crs crs[static 1])
Returns the number of empty rows of the crs.
uint32_t * NTW_CRS_getEmptyRowIndices (const ntw_crs crs[static 1], uint32_t *restrict outIndicesNum)
Returns a vector with the indices of empty rows of the crs.
double NTW_CRS_valueAt (const ntw_crs crs[static 1], uint32_t row, uint32_t col)
Returns the value at (row, col) of the matrix of the CRS.
void NTW_CRS_print (FILE *restrict stream, const ntw_crs crs[static 1])
A function for visualizing a CRS.
void NTW_CRS_printFullMatrix (FILE *restrict stream, const ntw_crs crs[static 1])
A function for printing the full matrix of the CRS.
Detailed Description
The definitions for the functions declared at ntw_crs.h .
Author
Katomeris Nikolaos, 8551, ngkat.nosp@m.omer.nosp@m.@auth.nosp@m..gr
Date
11-08-2018
Definition in file ntw_crs.c.
Function Documentation
NTW_CRS_cmult()
void NTW_CRS_cmult (ntw_crs crs[static 1], const double c)
Multiplies the values of the sparse table in the CRS form crs with the constant value c.
Parameters
crs The ntw_crs representation of the sparse table.
c The constant multiplicator.
Definition at line 42 of file ntw_crs.c.
References ntw_crs::edge_num, and ntw_crs::val.
Referenced by NTWPR_pagerank().
NTW_CRS_colNorm()
void NTW_CRS_colNorm (ntw_crs crs[static 1])
Normalizes the columns of the CRS table so they sum to one.
O(crs->edge_num) complexity.
Parameters
crs The CRS representation of the table.
Definition at line 112 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::edge_num, ntw_crs::node_num, and ntw_crs::val.
Referenced by NTWPR_pagerank().
NTW_CRS_free()
void NTW_CRS_free (ntw_crs * crs)
Unloads a ntw_crs from memory (frees allocated memory).
Parameters
crs
Definition at line 28 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::row_ptr, and ntw_crs::val.
NTW_CRS_getEmptyRowIndices()
uint32_t* NTW_CRS_getEmptyRowIndices (const ntw_crs crs[static 1], uint32_t *restrict outIndicesNum)
Returns a vector with the indices of empty rows of the crs.
Parameters
crs
outIndicesNum Pass the adress of a uint32_t to be filled with the size of the returned array.
Returns
uint32_t The number of empty rows in the crs matrix.
Definition at line 143 of file ntw_crs.c.
References ntw_crs::node_num, NTW_CRS_getEmptyRowsNum(), and ntw_crs::row_ptr.
NTW_CRS_getEmptyRowsNum()
uint32_t NTW_CRS_getEmptyRowsNum (const ntw_crs crs[static 1])
Returns the number of empty rows of the crs.
Parameters
crs
Returns
uint32_t The number of empty rows in the crs matrix.
Definition at line 133 of file ntw_crs.c.
References ntw_crs::node_num, and ntw_crs::row_ptr.
Referenced by NTW_CRS_getEmptyRowIndices().
NTW_CRS_new()
ntw_crs* NTW_CRS_new (const uint32_t nodeNum, const uint32_t edgeNum, uint32_t rowPtr[static nodeNum+1], uint32_t colInd[static edgeNum], double val[static edgeNum])
Creates a new CRS structure to store a matrix.
Should be freed using the NTW_CRS_free when non needed anymore.
Parameters
nodeNum The number of nodes (rows) of the matrix.
edgeNum The number of non-zero elements of the matrix.
rowPtr Array of nodeNum + 1 elements with the indeces of the val where each row begins and the end of the val array.
colInd Array of edgeNum elements with the columns of each non zero element of the matrix.
val Array of edgeNum elements with the non zero values of the matrix.
Returns
ntw_crs* The created struct or null if unsuccessful.
Definition at line 13 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::edge_num, ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.
Referenced by NTWPR_WGF_load2crs().
NTW_CRS_newTranspose()
ntw_crs* NTW_CRS_newTranspose (const ntw_crs crs[static 1])
Creates a new ntw_crs storing the transpose of crs.
... Allocates memory for the new ntw_crs that should be freed using the NTW_CRS_free when non needed anymore.
Parameters
crs
Returns
ntw_crs* Pointer to the created struct or null if unsuccessful.
Definition at line 37 of file ntw_crs.c.
NTW_CRS_print()
void NTW_CRS_print (FILE *restrict stream, const ntw_crs crs[static 1])
A function for visualizing a CRS.
Useful for debugging.
Parameters
stream Where will the output go.
crs The CRS to visualize.
Definition at line 180 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::edge_num, ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.
NTW_CRS_printFullMatrix()
void NTW_CRS_printFullMatrix (FILE *restrict stream, const ntw_crs crs[static 1])
A function for printing the full matrix of the CRS.
Useful for debugging. Avoid using it for \(nodes > 10000\).
Parameters
stream Where will the output go.
crs The CRS of the matrix that will be visualized.
Definition at line 200 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.
NTW_CRS_rowNorm()
void NTW_CRS_rowNorm (ntw_crs crs[static 1])
Normalizes the rows of the CRS table so they sum to one.
Parameters
crs The CRS representation of the table.
Definition at line 85 of file ntw_crs.c.
References ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.
NTW_CRS_rowNormUnif()
void NTW_CRS_rowNormUnif (ntw_crs crs[static 1])
Normalizes the rows of the CRS table giving all the edges in each row the same value in order to sum to one.
Parameters
crs The CRS representation of the table.
Definition at line 97 of file ntw_crs.c.
References ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.
NTW_CRS_valueAt()
double NTW_CRS_valueAt (const ntw_crs crs[static 1], uint32_t row, uint32_t col)
Returns the value at (row, col) of the matrix of the CRS.
Use it sparingly because it's relatively slow. (Depends on how sparse the row is with O(n) where n is the non-zero elements of the row).
Parameters
crs The CRS data.
row The row of the returned value.
col The column of the returned value.
Returns
double The value at [row, col]
Definition at line 168 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::row_ptr, and ntw_crs::val.
NTW_CRS_vmult()
void NTW_CRS_vmult (const ntw_crs crs[static 1], const double vector[static 1], double product[static crs->node_num])
Calculates the product of the CRS table crs with the vector and stores the result in product.
Parameters
crs The CRS representation of the matrix \(A\).
vector The vector \(v\).
product The product \(A*v\).
Definition at line 50 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.
Referenced by NTW_CRS_vmultAlloc().
NTW_CRS_vmultAlloc()
double* NTW_CRS_vmultAlloc (const ntw_crs crs[static 1], const double vector[static 1])
Calculates the product of the CRS table crs with the vector and return the result.
The memory of the result should be freed afterwards.
Parameters
crs The CRS representation of the matrix \(A\).
vector The vector \(v\).
Returns
double* The product vector \(A*v\).
Definition at line 61 of file ntw_crs.c.
References ntw_crs::node_num, and NTW_CRS_vmult().
NTW_CRS_vmultTranspose()
void NTW_CRS_vmultTranspose (const ntw_crs crs[static 1], const double vector[static 1], double product[static 1])
Calculates the product of the transpose of the CRS table crs with the vector and stores the result in product.
Parameters
crs The CRS representation of the matrix \(A\).
vector The vector \(v\).
product The product \(A^T*v\).
Definition at line 74 of file ntw_crs.c.
References ntw_crs::col_ind, ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.