Parallel pagerank: /home/ecat/nikos/parallel/src/ntwpr_wg.c File Reference
ntwpr_wg.c File Reference
File containing the implementations of ntwpr_wg.h.
#include "../include/ntwpr_wg.h"
#include <stdio.h>
Functions
ntw_crs * NTWPR_WGF_load2crs (NTWPR_WGFile *restrict wgf)
Loads a web graph in memory using the CRS data structure.
NTWPR_WGFile * NTWPR_WGF_fopen (const char path[static 1])
Creates a new WGFile at path.
int NTWPR_WGF_fclose (NTWPR_WGFile *wgfile)
Closes the NTWPR_WGFile stream and frees memory.
unsigned NTWPR_WGF_rewind (NTWPR_WGFile *const wgf)
Reset the wgf struct to read the edges again.
void NTWPR_WGF_exportFM (NTWPR_WGFile *restrict wgfp, const char exportPath[static 1], uint32_t nodeNum)
Exports the full graph matrix of a NTWPR_WGFile to the file at exportPath.
void NTWPR_WGF_exportSM (NTWPR_WGFile *restrict wgfp, const char exportPath[static 1], uint32_t nodeNum)
Exports the edges to a text file at exportPath.
void NTWPR_WGF_convert2Transpose (const char origWGFPath[static 1], const char exportWGFPath[static 1])
Creates a web graph file with the transpose of the web graph in origWGFPath.
void NTWPR_WGF_convertSU (const char suDataPath[static 1], const char exportPath[static 1], uint32_t nodeNum)
Converts web graph files from the format Stanford U. (SU) used to the NTWPR_WGFile' edge_data file format.
void NTWPR_WGF_transposeEdges (const size_t n, NTWPR_WGEdge edges[static n])
Transposes the edges of a graph described with edges.
int NTWPR_WGF_edgeCompare (const void *restrict edgeA, const void *restrict edgeB)
Compares two edges, used for sorting with qsort().
int NTWPR_WGF_edgeCompareForT (const void *restrict edgeA, const void *restrict edgeB)
Compares two edges, used for sorting with qsort().
Detailed Description
File containing the implementations of ntwpr_wg.h.
Author
Katomeris Nikolaos, 8551, ngkat.nosp@m.omer.nosp@m.@auth.nosp@m..gr
Date
10-08-2018
Definition in file ntwpr_wg.c.
Function Documentation
NTWPR_WGF_convert2Transpose()
void NTWPR_WGF_convert2Transpose (const char origWGFPath[static 1], const char exportWGFPath[static 1])
Creates a web graph file with the transpose of the web graph in origWGFPath.
If the path is the same the file will be replaced.
Parameters
origWGFPath The path of the web graph file containing the graph \(G\).
exportWGFPath The path of the web graph file that will contain the output graph \(G^T\).
Definition at line 214 of file ntwpr_wg.c.
References NTWPR_WGFile::edge_data, NTWPR_WGFile::edge_num, NTWPR_WGFile::node_num, NTWPR_WGF_edgeCompareForT(), NTWPR_WGF_fclose(), NTWPR_WGF_fopen(), and NTWPR_WGF_transposeEdges().
NTWPR_WGF_convertSU()
void NTWPR_WGF_convertSU (const char suDataPath[static 1], const char exportPath[static 1], uint32_t nodeNum)
Converts web graph files from the format Stanford U. (SU) used to the NTWPR_WGFile' edge_data file format.
Extra: The output can be loaded into MATLAB with: fread(file_id, [2,inf], 'uint32')';
Parameters
suDataPath The input file's path..
exportPath The output file's path.
nodeNum The number of nodes that will be in the graph matrix. (Enter 0 to get all the nodes of the file.)
Definition at line 265 of file ntwpr_wg.c.
References LINE_COMMENT_SU, NTWPR_invalid_fp_exit, and NTWPR_WGF_edgeCompare().
NTWPR_WGF_edgeCompare()
int NTWPR_WGF_edgeCompare (const void *restrict edgeA, const void *restrict edgeB)
Compares two edges, used for sorting with qsort().
Parameters
edgeA
edgeB
Returns
int edgeA->nodeA - edgeB->nodeB
Definition at line 376 of file ntwpr_wg.c.
References NTWPR_WGEdge::nodeA.
Referenced by NTWPR_WGF_convertSU().
NTWPR_WGF_edgeCompareForT()
int NTWPR_WGF_edgeCompareForT (const void *restrict edgeA, const void *restrict edgeB)
Compares two edges, used for sorting with qsort().
Parameters
edgeA
edgeB
Returns
int edgeA->nodeA - edgeB->nodeB
Definition at line 384 of file ntwpr_wg.c.
References NTWPR_WGEdge::nodeB.
Referenced by NTWPR_WGF_convert2Transpose().
NTWPR_WGF_exportFM()
void NTWPR_WGF_exportFM (NTWPR_WGFile *restrict wgfp, const char exportPath[static 1], uint32_t nodeNum)
Exports the full graph matrix of a NTWPR_WGFile to the file at exportPath.
Should be used with caution and for relatively small nodeNum. (nodeNum \(< 10000 \))
Parameters
wgfp The input NTWPR_WGFile pointer.
exportPath The output file's path.
nodeNum The max number of nodes that will be in the graph matrix.
Definition at line 96 of file ntwpr_wg.c.
References NTWPR_invalid_fp_exit, and NTWPR_WGF_rewind().
NTWPR_WGF_exportSM()
void NTWPR_WGF_exportSM (NTWPR_WGFile *restrict wgfp, const char exportPath[static 1], uint32_t nodeNum)
Exports the edges to a text file at exportPath.
Extra: Can be loaded into a sparse MATLAB matrix using:
     > load -ASCII exported_file_path
     > sparce(file_name(:,1)+1, file_name(:,2)+1, ...
     ones(size(file_name, 1), 1), node_num, node_num)
Parameters
wgfp The input NTWPR_WGFile pointer.
exportPath The output file's path.
nodeNum The max number of nodes that will be in the graph matrix.
Definition at line 175 of file ntwpr_wg.c.
References NTWPR_invalid_fp_exit, and NTWPR_WGF_rewind().
NTWPR_WGF_fclose()
int NTWPR_WGF_fclose (NTWPR_WGFile * wgfile)
Closes the NTWPR_WGFile stream and frees memory.
Parameters
wgfile The file to be closed.
Returns
int Returns 0 if succussful. On failure EOF is returned.
Definition at line 78 of file ntwpr_wg.c.
References NTWPR_WGFile::edge_data.
Referenced by NTWPR_WGF_convert2Transpose().
NTWPR_WGF_fopen()
NTWPR_WGFile* NTWPR_WGF_fopen (const char path[static 1])
Creates a new WGFile at path.
The WGFile should be then closed with NTWPR_WGfclose()
Parameters
path The path of the file.
Returns
NTWPR_WGFile* The struct containing the file created.
Definition at line 56 of file ntwpr_wg.c.
References NTWPR_WGFile::edge_data, NTWPR_WGFile::edge_num, NTWPR_WGFile::node_num, and NTWPR_invalid_fp_exit.
Referenced by NTWPR_WGF_convert2Transpose().
NTWPR_WGF_load2crs()
ntw_crs* NTWPR_WGF_load2crs (NTWPR_WGFile *restrict wgf)
Loads a web graph in memory using the CRS data structure.
The CRS structure's memory should be freed with NTWPR_CRSfree() later.
Parameters
wgf The input web graph data.
Returns
ntw_crs* pointing to the loaded CRS or null.
Definition at line 11 of file ntwpr_wg.c.
References ntw_crs::node_num, NTW_CRS_new(), and NTWPR_WGF_rewind().
NTWPR_WGF_rewind()
unsigned NTWPR_WGF_rewind (NTWPR_WGFile *const wgf)
Reset the wgf struct to read the edges again.
Parameters
wgf The NTWPR_WGFile struct.
Returns
true If successful.
false If an error occured.
Definition at line 91 of file ntwpr_wg.c.
References NTWPR_WGFile::edge_data.
Referenced by NTWPR_WGF_exportFM(), NTWPR_WGF_exportSM(), and NTWPR_WGF_load2crs().
NTWPR_WGF_transposeEdges()
void NTWPR_WGF_transposeEdges (const size_t n, NTWPR_WGEdge edges[static n])
Transposes the edges of a graph described with edges.
Parameters
n The number of edges in the graph.
edges The edges of the graph.
Definition at line 366 of file ntwpr_wg.c.
Referenced by NTWPR_WGF_convert2Transpose().