Parallel pagerank: /home/ecat/nikos/parallel/include/ntwpr.h File Reference
ntwpr.h File Reference
Methods for calculating the pagerank of web graphs.
#include "ntwpr_wg.h"
Functions
double * NTWPR_pagerank (ntw_crs webGraph[static 1], double c, double e, FILE *stream)
Calculates the pagerank of the nodes of a web graph.
double NTWPR_GS_iter (const ntw_crs matrix[static 1], double x_vec[static 1], const double b_vec[static 1], const uint32_t m, const size_t d[static m])
Calculates one iteration of \((I-A)x = b\).
double Vector_sqnorm (uint32_t size, double vector[static size])
Returns the squered norm of a vector.
Detailed Description
Methods for calculating the pagerank of web graphs.
Author
Katomeris Nikolaos, 8551, ngkat.nosp@m.omer.nosp@m.@auth.nosp@m..gr
Date
11-08-2018
Definition in file ntwpr.h.
Function Documentation
NTWPR_GS_iter()
double NTWPR_GS_iter (const ntw_crs matrix[static 1], double x_vec[static 1], const double b_vec[static 1], const uint32_t m, const size_t d[static m])
Calculates one iteration of \((I-A)x = b\).
Uses the Gauss-Sneidel method, using forward substitution.
\[\vec{x}_i^{k+1} = \frac{1}{1-a_{ii}}(b_i - \sum_{j=1}^{i-1} a_{ij}\vec{x}_j^{k+1} + \sum_{j=i+1}^{n} a_{ij}\vec{x}_j^k)\]
Parameters
matrix The sparse matrix A in CRS form.
x_vec The vector x that will be replaced.
b_vec The vector b.
m The size of the vector d.
d The vector containing the "dangling node"' indices of matrix.
Returns
double The squared norm difference of the old and new x_vec.
Definition at line 58 of file ntwpr.c.
References ntw_crs::col_ind, ntw_crs::node_num, ntw_crs::row_ptr, and ntw_crs::val.
Referenced by NTWPR_pagerank().
NTWPR_pagerank()
double* NTWPR_pagerank (ntw_crs webGraph[static 1], double c, double e, FILE * stream)
Calculates the pagerank of the nodes of a web graph.
Parameters
webGraph The web graf in ntw_crs representation.
c The teleportation coefficient.
e The converge tolerance.
stream Opened FILE* stream for printing results.
Returns
double* The calculated pagerank vector.
DEBUG:* NTWM_CRS_printFullMatrix(stdout, webGraph);
DEBUG:* NTWM_CRS_printFullMatrix(stdout, webGraph);
DEBUG:* NTWM_CRS_printFullMatrix(stdout, webGraph);
DEBUG:* NTWM_printDV(stdout, wgSize, b, 4);
Definition at line 13 of file ntwpr.c.
References ntw_crs::node_num, NTW_CRS_cmult(), NTW_CRS_colNorm(), NTW_CRS_getEmptyRowIndices(), NTW_DEBUG_printElapsedTime(), NTWM_newUniVectorD(), and NTWPR_GS_iter().
Vector_sqnorm()
double Vector_sqnorm (uint32_t size, double vector[static size])
Returns the squered norm of a vector.
Parameters
size The vector's size.
vector The vector.
Returns
double The vector's second norm squared.