Parallel pagerank: /home/ecat/nikos/parallel/src/ntwpr.c File Reference
ntwpr.c File Reference
File containing the definitions of the functions declared at ntwpr.h.
#include "../include/ntwpr.h"
#include "../include/ntw_math.h"
Functions
double * NTWPR_pagerank (ntw_crs webGraph[static 1], double c, double e, FILE *stream)
Calculates the pagerank of the nodes of a web graph.
double NTWPR_GS_iter (const ntw_crs matrix[static 1], double x_vec[static 1], const double b_vec[static 1], const uint32_t m, const size_t d[static m])
void NTWPR_pr_init (const uint32_t nodeNum, double vector[static nodeNum])
Initializes the pagerank vector uniformely.
Detailed Description
File containing the definitions of the functions declared at ntwpr.h.
Author
Katomeris Nikolaos, 8551, ngkat.nosp@m.omer.nosp@m.@auth.nosp@m..gr
Date
11-08-2018
Definition in file ntwpr.c.
Function Documentation
NTWPR_pagerank()
double* NTWPR_pagerank (ntw_crs webGraph[static 1], double c, double e, FILE * stream)
Calculates the pagerank of the nodes of a web graph.
Parameters
webGraph The web graf in ntw_crs representation.
c The teleportation coefficient.
e The converge tolerance.
Returns
double* The calculated pagerank vector.
DEBUG:* NTWM_CRS_printFullMatrix(stdout, webGraph);
DEBUG:* NTWM_CRS_printFullMatrix(stdout, webGraph);
DEBUG:* NTWM_CRS_printFullMatrix(stdout, webGraph);
DEBUG:* NTWM_printDV(stdout, wgSize, b, 4);
Definition at line 11 of file ntwpr.c.
References ntw_crs::node_num, NTW_CRS_cmult(), NTW_CRS_colNorm(), NTW_CRS_getEmptyRowIndices(), NTWM_newUniVectorD(), and NTWPR_GS_iter().
NTWPR_pr_init()
void NTWPR_pr_init (const uint32_t nodeNum, double vector[static nodeNum])
Initializes the pagerank vector uniformely.
Parameters
nodeNum The number of nodes (size of the vector).
vector The vector that will be initialized.
Definition at line 83 of file ntwpr.c.